#!/bin/zsh

# merge in defaults and keymaps

# system wide
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f $sysresrouces ]] && xrdb -merge $sysresrouces
[[ -f $sysmodmap ]] && xmodmap $sysmodmap

# user specific
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
[[ -f $userresources ]] && xrdb -merge $userresources
[[ -f $usermodmap ]] && xmodmap $usermodmap

# load system wide inits
if [[ -d /etc/X11/xinit/xinitrc.d ]] ; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
    [[ -x "$f" ]] && emulate sh -c "source $f"
  done
  unset f
fi

[[ -f ~/.pathrc ]] && . ~/.pathrc

exec i3
